// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2UVR7RWwg6jWUV3LMzbRAdNTxqt9TAPI',
    appId: '1:1097709091709:web:cb26e9ef2b1a786dbfea14',
    messagingSenderId: '1097709091709',
    projectId: 'couplet-rk',
    authDomain: 'couplet-rk.firebaseapp.com',
    storageBucket: 'couplet-rk.appspot.com',
    measurementId: 'G-9XNTYDPT2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Ct8chU78f6Ek1XStIKJBI2fvMITzD8w',
    appId: '1:1097709091709:android:98e18468804b26d6bfea14',
    messagingSenderId: '1097709091709',
    projectId: 'couplet-rk',
    storageBucket: 'couplet-rk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbDAwGKWPgLS3SEZqpCOA1k6y_HIEKIc',
    appId: '1:1097709091709:ios:ce50a8a5cb4ebee2bfea14',
    messagingSenderId: '1097709091709',
    projectId: 'couplet-rk',
    storageBucket: 'couplet-rk.appspot.com',
    iosBundleId: 'com.example.couplet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbDAwGKWPgLS3SEZqpCOA1k6y_HIEKIc',
    appId: '1:1097709091709:ios:2193101e68a722eabfea14',
    messagingSenderId: '1097709091709',
    projectId: 'couplet-rk',
    storageBucket: 'couplet-rk.appspot.com',
    iosBundleId: 'com.example.couplet.RunnerTests',
  );
}
